
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - bridge_network  
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: sh -c "/entrypoint.sh && uwsgi --http 0.0.0.0:8000 --wsgi-file ./parrotsite/wsgi.py"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - bridge_network
    depends_on:
          - db
    restart: unless-stopped
    volumes:
      - app:/app

networks:
  bridge_network:
    driver: bridge

volumes:
    postgres_data: {}
    app: {}
